### ISSUE TITLE
limit to number of quotes?

### ISSUE THREAD

**Issue by bachoo786** [KirAsh4/random_quotes#2]
Hi 

I have many quotes and I have inserted them all in my random_quotes.js file. However, I believe there is a limit to the number of quotes the .js file can have. Because when I pass a certain number of quotes the module stops working. Is that correct?

Is it possible to remove this limitation?

Thanks.

**Comment by KirAsh4** [comment]
There isn't a limitation in the code. Mine has about 10k quotes in it and runs with no issues. However, you may want to look at your quotes and check for characters that may need to be escaped. For example, apostrophes need escaping, so words like `don't` need to be escaped as `don\'t` ...
